# Generated by Django 4.2.20 on 2025-04-01 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="created_at",
            new_name="creatd_at",
        ),
    ]
