# Generated by Django 4.2.20 on 2025-04-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_created_at_user_creatd_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="old_cart",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
