# Generated by Django 4.2.20 on 2025-04-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_is_sale_product_sale_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="upload/product"),
        ),
    ]
