# Generated by Django 4.2.20 on 2025-04-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sale_price",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
