"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-0gzzd&b5#)f2**v7dn@^-w&1=6%l1y=iynu3iks+rj)yp!85wu"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",  # dev_5 쉼표(,)를 추가하여 통화 형식(₩1,000,000)으로 변환하는 방법
    "store",  # dev_1
    "accounts",  # dev_9
    "cart",  # dev_15
    "orders",  # dev_24
    "payment",  # dev_26
    # dev_27 소셜로그인
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    # provider 추가 (추가로 다른 사이트도 하고 싶을 경우 뒤에 이름만 변경하면 됨)
    #'allauth.socialaccount.providers.google', #구글로그인 구현시 추가
    "allauth.socialaccount.providers.kakao",  # 카카오로그인 구현시 추가
    #'allauth.socialaccount.providers.naver', # 네이버 로그인 구현시 추가
    # dev_28
    "rest_framework", #DRF 
    "api",
    "corsheaders",  # dev_3_Fruit
    "djoser", # dev_5_Fruit
    #dev_9_1_Fruit REST API 기반 소셜로그인
    "rest_framework.authtoken",
    "dj_rest_auth", # REST API 기반 소셜 로그인 모듈
    "dj_rest_auth.registration", #회원 가입 모듈
    "drf_spectacular",#dev_11_Fruit
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # dev_3_Fruit
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",  # #dev_27 추가
]

# dev_3_Fruit
# 정확히 허용할 도메인만
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",  # 프론트 도메인
# ]
CORS_ORIGIN_ALLOW_ALL = True  # 개발 환경에서만 사용. 프로덕션에서는 특정 도메인만 허용하도록 변경 필요


ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # dev_1
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # dev_17 cart(request)가 모든 템플릿에서 사용 가능해짐.
                "cart.context_processors.cart",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    # },
    # {
    #     "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    # },
    # {
    #     "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    # },
    # {
    #     "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "ko-kr"  # dev_1

TIME_ZONE = "Asia/Seoul"  # dev_1

USE_I18N = True

# dev_5
# Timezone의 사용여부를 정한다.
# False면 모든 datetime들을 표시하고 True면 template과 form에만 적용된다.
# 즉 DB에 저장되는 정보도 한국 시간대로 사용하려면 이 부분을 False로 지정해주어야 한다.
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# dev_2
# 스태틱(static) 디렉터리
# URL 상의 스택틱 폴더를 ,로컬(내컴퓨터)의 파일 폴더와 매칭 시키는 부분
# http://127.0.0.1:8000/static/a.jpg
STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 미디어 파일 경로 설정
import os

# dev_2
# http://127.0.0.1:8000/media/파일경로
MEDIA_URL = "media/"  # ex) /media/photo1.png
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# dev_9
# 다시 한번 migrate 시켜줘야함
AUTH_USER_MODEL = "accounts.User"

# dev_15
CART_SESSION_ID = "cart"

# dev_27
# 위에서 추가되어 있으므로
# AUTH_USER_MODEL = "accounts.User"
# 추가!! 없으면 오류 발생 "앱이름.모델명" user모델생성 후 allauth말고 내가 생성한 모델을 우선으로 적용
SITE_ID = 1  # 추가

# dev_27
AUTHENTICATION_BACKENDS = [
    # 추가 장고에서 사용자의 이름을 기준으로 로그인하도록 설정
    "django.contrib.auth.backends.ModelBackend",
    # 추가 'allauth'의 인증방식 추가
    "allauth.account.auth_backends.AuthenticationBackend",
]


# dev_27 소셜로그인 설정
# 소셜 로그인 시 GET 요청만으로 로그인 처리를 허용
# 사용자가 로그인 버튼을 클릭했을 때 redirect URI로 오는 GET 요청만으로도 자동 로그인
SOCIALACCOUNT_LOGIN_ON_GET = True
ACCOUNT_LOGOUT_REDIRECT_URL = (
    "/"  # 로그아웃 한 뒤에 어느 페이지로 리다이렉트할지 경로를 설정
)
ACCOUNT_LOGOUT_ON_GET = True

# dev_27 로그인후 리다이렉트
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"


# pip install python-decouple
from decouple import config

# dev_27 소셜로그인 설정
SOCIALACCOUNT_PROVIDERS = {
    # 추가 카카오 설정
    "kakao": {
        "APP": {
            "client_id": config("KAKAO_CLIENT_ID"),
            "secret": config("KAKAO_SECRET"),
            "key": "",
        },
        # scope의 경우 내가 어떤 데이터를 가져올건지를 선택하는 것인데 사이트마다
        # 제공하는 값이 다르기 때문에 가져올 데이터를 설정한 이후 추가/삭제 해보면 됩니다.
        # SCOPE값에 제공하지 않는 값을 넣거나 하는 이유로 오류가 나올 수 있음
        "SCOPE": [
            #dev_9_1_Fruit
            "account_email",
            "profile",
            "gender",
        ],
        # 추가
        "AUTH_PARAMS": {
            "access_type": "online",  # 추가
            "prompt": "select_account",  # 추가 간편로그인을 지원해줌
        },
    }
}


# dev_5_Fruit

# 대략적인 구현
# class JWTAuthentication(BaseAuthentication):
#     def authenticate(self, request):
#         header = self.get_header(request)  # Authorization 헤더 추출
#         raw_token = self.get_raw_token(header)  # "Bearer abc.def.ghi" → 토큰만 추출
#         validated_token = self.get_validated_token(raw_token)  # 유효성 검사
#         user = self.get_user(validated_token)  # payload에서 user_id를 추출 → User 객체
#         return (user, validated_token)

#JWTAuthentication은 다음을 자동으로 처리
#HTTP 요청의 Authorization 헤더에서 JWT 토큰을 추출
#그 토큰을 디코딩해서 유효한지 검사
#토큰에서 사용자 ID를 추출하고, 해당 사용자를 DB에서 가져옴
#해당 사용자를 request.user에 할당
#DRF에서 모든 API 뷰가 사용할 기본 인증 클래스들을 지정 

#http://127.0.0.1:8000/api/product-list/?page=2
#http://127.0.0.1:8000/api/categories/?page=1

# Django REST Framework (DRF) 
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        #"rest_framework_simplejwt.authentication.JWTAuthentication",
        "dj_rest_auth.jwt_auth.JWTCookieAuthentication", #dev_9_2_Fruit
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",#dev_11_Fruit
}

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=3), #timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# 도져(djoser) 커스텀마이징 세팅
DJOSER = {
    "USER_ID_FIELD": "id",
    "LOGIN_FIELD": "username",  # 또는 email
    "SERIALIZERS": {
        "user_create": "accounts.serializers.UserCreateSerializer",
        "user": "accounts.serializers.UserSerializer",
        "current_user": "accounts.serializers.UserSerializer",
    },
    "CREATE_SESSION_ON_LOGIN": True,  # 로그인하면 세션도 생성됨
}

# dev_9_1_Fruit
# dj_rest_auth 을 위한 세팅
SOCIALACCOUNT_ADAPTER = "accounts.adapters.KakaoSocialAccountAdapter"
# 3.0.0버전 이상
#dev_9_2_Fruit
REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_HTTPONLY": True, 
    'JWT_AUTH_REFRESH_COOKIE' : "refresh_token", 
    'SESSION_LOGIN' :False, 
    'JWT_AUTH_SAMESITE': 'Lax',
    'JWT_AUTH_COOKIE_USE_CSRF' : False, 
    #시리얼라이져 세팅
    'USER_DETAILS_SERIALIZER': "accounts.serializers.UserResAuthSerializer",
    'REGISTER_SERIALIZER': 'accounts.serializers.UserRegisterRestAuthSerializer',
}

# dev_9_2_Fruit
#브라우저는 axios의 withCredentials: true 요청 시 쿠키를 포함해 전송
CORS_ALLOW_CREDENTIALS = True

# 로그인 방식: 이메일로 로그인
ACCOUNT_AUTHENTICATION_METHOD = "username_email"
ACCOUNT_USERNAME_REQUIRED = False  # username 필요 없음
ACCOUNT_EMAIL_REQUIRED = True  # 이메일 필수
ACCOUNT_USER_MODEL_USERNAME_FIELD = "username"  # username을 필드로 씀

# 이메일 인증 건너뛰기 (선택)
ACCOUNT_EMAIL_VERIFICATION = "none"  # 개발 중에는 'none' 추천
ACCOUNT_LOGOUT_ON_GET = True 
SOCIALACCOUNT_LOGIN_ON_GET = True #브라우저에서 단순히 링크 클릭이나 리다이렉트로 로그아웃을 시킬 수 있게 하려면 GET 요청을 허용해야 함.

# # 개발 환경이면 False, 운영이면 True
# CSRF_COOKIE_SECURE = False
# SESSION_COOKIE_SECURE = False

#dev_11_Fruit
SPECTACULAR_SETTINGS = {
    # General schema metadata. Refer to spec for valid inputs
    # https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#openapi-object
    'TITLE': 'drf-spectacular API Document',
    'DESCRIPTION': 'drf-specatular 를 사용해서 만든 API 문서입니다.',
    'SWAGGER_UI_SETTINGS': {
        'dom_id': '#swagger-ui',
        'layout': 'BaseLayout', 
        'deepLinking': True,  
        'displayOperationId': True,
        'filter': True,
    },
   
    'LICENSE': {
        'name': 'MIT License',
    },
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,

    'SWAGGER_UI_DIST': '//unpkg.com/swagger-ui-dist@3.38.0',

    'CONTACT': {
        'name': 'John Doe',
        'email': 'johndoe@example.com',
        'url': 'https://www.example.com',
    }
}